/* This file is automatically generated. Do not edit. */

#include "ien_us.h"
#include "izh_cn.h"
#include "izh_ms.h"
#include "izh_wy.h"

#include <string.h>

#ifndef CMD_LANGUAGES_H
#define CMD_LANGUAGES_H

static void cmd_i18n_init_table(const char *lang, const char **table)
{
    if (0)
    {
    }
    else if (memcmp(lang, "en_us", strlen("en_us")) == 0)
    {
        lang_en_us_init(table);
    }
    else if (memcmp(lang, "zh_cn", strlen("zh_cn")) == 0)
    {
        lang_zh_cn_init(table);
    }
    else if (memcmp(lang, "zh_ms", strlen("zh_ms")) == 0)
    {
        lang_zh_ms_init(table);
    }
    else if (memcmp(lang, "zh_wy", strlen("zh_wy")) == 0)
    {
        lang_zh_wy_init(table);
    }
    else
    {
        lang_en_us_init(table);
    }
}

#endif
