#!/usr/bin/env python3
# Copyright (C) 2026 ChenPi11
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate C code for internationalization language list."""

import sys


def main() -> None:
    """Generate C code for internationalization language list."""
    supported_langs = sorted([lang.lower() for lang in sys.argv[1:]])
    out_lines = [
        "/* This file is automatically generated. Do not edit. */",
        "",
    ]
    for lang in supported_langs:
        out_lines.append(f'#include "i{lang}.h"')
    out_lines.extend(
        [
            "",
            "#include <string.h>",
            "",
            "#ifndef CMD_LANGUAGES_H",
            "#define CMD_LANGUAGES_H",
            "",
            "static void cmd_i18n_init_table(const char *lang, const char **table)",
            "{",
            "    if (0)",
            "    {",
            "    }",
        ],
    )
    for lang in supported_langs:
        out_lines.extend(
            [
                f'    else if (memcmp(lang, "{lang}", strlen("{lang}")) == 0)',
                "    {",
                f"        lang_{lang}_init(table);",
                "    }",
            ]
        )
        sys.stderr.write(f"{lang} ")
        sys.stderr.flush()
    out_lines.extend(
        [
            "    else",
            "    {",
            "        lang_en_us_init(table);",
            "    }",
            "}",
            "",
            "#endif",
        ]
    )

    sys.stdout.write("\n".join(out_lines) + "\n")
    sys.stderr.write("\n")

if __name__ == "__main__":
    main()
