#!/usr/bin/env python3
# Copyright (C) 2026 ChenPi11
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate C code for internationalization message table."""

import sys

NON_ASCII_MIN = 128


def encode_msg(msg: str, encode: str) -> str:
    """Encode a message string into a C-compatible string literal.

    escaping non-ASCII characters.
    """
    result: list[str] = []
    for ch in msg:
        code = ord(ch)
        if code < NON_ASCII_MIN:
            result.append(ch)
        else:
            result.extend([f"\\{b:03o}" for b in ch.encode(encode)])
    return "".join(result)


def generate_c_code(
    lang: str,
    encode: str,
    messages: list[tuple[str, list[str]]],
) -> list[str]:
    """Generate C code for internationalization message table."""
    func_name = f"lang_{lang.lower()}_init"
    out_lines = [
        "/* This file is automatically generated. Do not edit. */",
        f"/* Language: {lang}, Encoding: {encode} */",
        '#include "imessages.h"',
        "",
        f"#ifndef LANG_{lang.upper()}_H",
        f"#define LANG_{lang.upper()}_H",
        "",
        f"static void {func_name}(const char *table[MSG_COUNT])",
        "{",
    ]

    for msg_id, strings in messages:
        if len(strings) == 1:
            out_lines.append(f"    table[{msg_id}] = {encode_msg(strings[0], encode)};")
        else:
            out_lines.append(f"    table[{msg_id}] =")
            for i, s in enumerate(strings):
                if i == len(strings) - 1:
                    out_lines.append(f"        {encode_msg(s, encode)};")
                else:
                    out_lines.append(f"        {encode_msg(s, encode)}")

    out_lines.extend(
        [
            "}",
            "#endif",
            "",
        ],
    )

    return out_lines


ARGS_COUNT = 2


def main() -> None:
    """Generate C code for internationalization message table."""
    if len(sys.argv) != ARGS_COUNT:
        sys.stderr.write("Usage: ti18ntbl <encoding>\n")
        sys.exit(1)
    encode = sys.argv[1]

    data: str = sys.stdin.read()
    parts = data.split("---")

    lang = "ERR"
    if parts and parts[0].strip():
        first_lines = parts[0].strip().splitlines()
        if first_lines:
            lang = first_lines[0].strip()

    messages: list[tuple[str, list[str]]] = []
    for part in parts[1:]:
        lines = [line for line in part.splitlines() if line.strip()]
        if not lines:
            continue

        msg_id = lines[0].strip()
        if not msg_id.startswith("MSG_"):
            sys.stderr.write(f"Error: Invalid message ID '{msg_id}'\n")
            sys.exit(1)

        strings: list[str] = []
        for line in lines[1:]:
            stripped = line.lstrip()
            if stripped.startswith('"'):
                strings.append(stripped)

        if strings:
            messages.append((msg_id, strings))

    out_lines = generate_c_code(lang, encode, messages)

    sys.stdout.write("\n".join(out_lines))
    sys.stderr.write(f"Generated {len(messages)} messages.\n")


if __name__ == "__main__":
    main()
